export const FETCH_EMPLOYEES_REQUEST: 'FETCH_EMPLOYEES_REQUEST' = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS' = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE: 'FETCH_EMPLOYEES_FAILURE' = 'FETCH_EMPLOYEES_FAILURE';
export const TOGGLE_EXPANDED_ROW: 'TOGGLE_EXPANDED_ROW' = 'TOGGLE_EXPANDED_ROW';
export const FETCH_VERISOURCE_EMPLOYEES_REQUEST: 'FETCH_VERISOURCE_EMPLOYEES_REQUEST' =
  'FETCH_VERISOURCE_EMPLOYEES_REQUEST';
export const FETCH_VERISOURCE_EMPLOYEES_SUCCESS: 'FETCH_VERISOURCE_EMPLOYEES_SUCCESS' =
  'FETCH_VERISOURCE_EMPLOYEES_SUCCESS';
export const FETCH_VERISOURCE_EMPLOYEES_FAILURE: 'FETCH_VERISOURCE_EMPLOYEES_FAILURE' =
  'FETCH_VERISOURCE_EMPLOYEES_FAILURE';
export const LINK_EMPLOYEES: 'LINK_EMPLOYEES' = 'LINK_EMPLOYEES';
export const CANCEL_LINK_EMPLOYEES: 'CANCEL_LINK_EMPLOYEES' = 'CANCEL_LINK_EMPLOYEES';
export const LINK_EMPLOYEES_REQUEST: 'LINK_EMPLOYEES_REQUEST' = 'LINK_EMPLOYEES_REQUEST';
export const LINK_EMPLOYEES_FAILURE: 'LINK_EMPLOYEES_FAILURE' = 'LINK_EMPLOYEES_FAILURE';
export const LINK_EMPLOYEES_SUCCESS: 'LINK_EMPLOYEES_SUCCESS' = 'LINK_EMPLOYEES_SUCCESS';
export const FETCH_VERISOURCE_EMPLOYEE_REQUEST: 'FETCH_VERISOURCE_EMPLOYEE_REQUEST' =
  'FETCH_VERISOURCE_EMPLOYEE_REQUEST';
export const FETCH_VERISOURCE_EMPLOYEE_FAILURE: 'FETCH_VERISOURCE_EMPLOYEE_FAILURE' =
  'FETCH_VERISOURCE_EMPLOYEE_FAILURE';
export const FETCH_VERISOURCE_EMPLOYEE_SUCCESS: 'FETCH_VERISOURCE_EMPLOYEE_SUCCESS' =
  'FETCH_VERISOURCE_EMPLOYEE_SUCCESS';
